@host = localhost
@port = 3333
@url = http://localhost:3333

### Create Student
POST {{url}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "Diego",
  "lastname": "Bonito",
  "course": "Ciência da Computação",
  "github": "BonitoDiego03",
  "email": "bonitodiego03@teste.com",
  "hardskills": [
    {
      "name": "Node"
    },
    {
      "name": "PHP"
    }
  ],
  "softskills": [
    {
      "name": "Inteligente"
    }
  ],
  "projects": [
    {
    "name": "Site",
    "description": "Fez o Back-End da aplicação"
    },
    {
      "name": "other",
      "description": "other things"
    }
  ]
}

### Get Student
GET {{url}}/get-student/43a028f9-3569-4542-9336-4690ec698119 HTTP/1.1