@host = localhost
@port = 3333
@url = http://localhost:3333

### Create Student
POST {{url}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "André",
  "lastname": "Silva",
  "course": "Ciência da Computação",
  "github": "Andre-Silva",
  "email": "andre@teste.com",
  "hardskills": ["React", "TypeScript", "Tawild", "Next"],
  "softskills": ["Prestativo", "Trabalho em equipe", "Organização"]
}

### Get Student
GET {{url}}/get-student/55d8ccee-54fb-4322-a9d0-d429386a3416 HTTP/1.1