@host = localhost
@port = 3333
@url = http://localhost:3333

### Create Student
POST {{url}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "lastname": "Doe",
  "course": "Computer Science",
  "github": "John-Doe",
  "email": "johndoe@teste.com",
  "hardskills": [
    {
      "name": "Node"
    },
    {
      "name": "Rust"
    }
  ],
  "softskills": [
    {
      "name": "Smart conversecion"
    },
    {
      "name": "Flexibel"
    }
  ],
  "projects": [
    {
    "name": "Web Site",
    "description": "Create the Back-End of the application"
    },
    {
      "name": "other",
      "description": "other things"
    }
  ]
}

### Get Student
GET {{url}}/get-student/cb81a1f2-b9b1-4bdb-b7a1-015ca1ca68a9 HTTP/1.1

### Get All Student
GET {{url}}/get-all HTTP/1.1